agribalise_columns = {
    "code_agb": "Code AGB",
    "code_ciqual": "Code CIQUAL",
    "groupe_aliment": "Groupe d'aliment",
    "sous_groupe_aliment": "Sous-groupe d'aliment",
    "nom_produit_fr": "Nom du Produit en Français",
    "lci_name": "LCI Name",
    "code_saison": "Code saison",
    "code_avion": "Code avion",
    "livraison": "Livraison",
    "materiau_emballage": "Matériau d'emballage",
    "preparation": "Préparation",
    "dqr": "DQR",
    "score_unique_ef": "Score unique EF",
    "changement_climatique": "Changement climatique",
    "appauvrissement_couche_ozone": "Appauvrissement de la couche d'ozone",
    "rayonnements_ionisants": "Rayonnements ionisants",
    "formation_photochimique_ozone": "Formation photochimique d'ozone",
    "particules_fines": "Particules fines",
    "effets_toxicologiques_non_cancero": "Effets toxicologiques sur la santé humaine : substances non-cancérogènes",
    "effets_toxicologiques_cancero": "Effets toxicologiques sur la santé humaine : substances cancérogènes",
    "acidification_terrestre_eaux_douces": "Acidification terrestre et eaux douces",
    "eutrophisation_eaux_douces": "Eutrophisation eaux douces",
    "eutrophisation_marine": "Eutrophisation marine",
    "eutrophisation_terrestre": "Eutrophisation terrestre",
    "ecotoxicite_eaux_douces": "Écotoxicité pour écosystèmes aquatiques d'eau douce",
    "utilisation_sol": "Utilisation du sol",
    "epuisement_ressources_eau": "Épuisement des ressources eau",
    "epuisement_ressources_energetiques": "Épuisement des ressources énergétiques",
    "epuisement_ressources_mineraux": "Épuisement des ressources minéraux",
}
